# GET http://localhost:5000/

# ###
# GET http://localhost:5000/courses

###
## Get all contacts
GET http://localhost:5000/contacts
###
##Get specific contact
GET http://localhost:5000/contacts/63c88c5f225c6e8df9f702e7


###
## Create new contact
POST http://localhost:5000/contacts
content-type: application/json

{
    "firstName": "Linda"
    , "lastName": "Owen"
    , "email": "sud86@hotmail.com"
    , "favoriteColor": "Unknown"
    , "birthday": "May 10 1986"
}



###
## update contact:
PUT http://localhost:5000/contacts/63c88c5f225c6e8df9f702e7
content-type: application/json

{
    "firstName": "Luisa"
    , "lastName": "Quispe"
    , "email": "sud86@hotmail.com"
    , "favoriteColor": "red"
    , "birthday": "May 10 1986"
}

###
## Delete a specific contact
DELETE http://localhost:5000/contacts/63cca4cceb1ebb35e5a5552d



//-----------------------------------------------------
//Production:
//-----------------------------------------------------



### 
GET https://week01.onrender.com/contacts

### 
GET https://week01.onrender.com/contacts/63c36852a937824528422e08

###
## update contact:
PUT https://week01.onrender.com/contacts/63c36802a937824528422e06
content-type: application/json

{
    "firstName": "Luisa"
    , "lastName": "Quispe"
    , "email": "sud86@hotmail.com"
    , "favoriteColor": "Green"
    , "birthday": "May 10 1986"
}

###
## Create new contact
POST https://week01.onrender.com/contacts
content-type: application/json

{
    "firstName": "Linda"
    , "lastName": "Owen"
    , "email": "sud86@hotmail.com"
    , "favoriteColor": "Unknown"
    , "birthday": "May 10 1986"
}


###
## Delete a specific contact
DELETE https://week01.onrender.com/contacts/63c36802a937824528422e06
